//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public string School { get; set; }
        public string Education_Level { get; set; }
        public string Department { get; set; }
        public string Program { get; set; }
        public int UserId { get; set; }
        public int EducationId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
