//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRelated
    {
        public int UserIdPrimary { get; set; }
        public int UserIdSecondary { get; set; }
        public Nullable<bool> FriendConfirm { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
