//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School_Department()
        {
            this.School_Program = new HashSet<School_Program>();
        }
    
        public int DepartmentId { get; set; }
        public string Department { get; set; }
        public Nullable<int> EducationId { get; set; }
    
        public virtual Education Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School_Program> School_Program { get; set; }
    }
}
