//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Program
    {
        public int ProgramId { get; set; }
        public string Program { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual School_Department School_Department { get; set; }
    }
}
